### ISSUE TITLE
Support for primereact 2.0.0-rc versions? (Support for Fullcalendar)

### ISSUE THREAD

**Issue by AlainD-** [primefaces/sigma#3]
Hi,
Is it foreseen to release soon a beta, or rc version of Sigma to support the early version 2.0.0-* of primereact? Noticebly the replacement of Schedule by Fullcalendar, among the other breaking changes.
By soon, I mean before the final version 2.0.0 of primereact is released.

Thank you.

**Comment by AlainD-** [comment]
I'm sorry what? I don't see the relation with the topic. It seems to me that you posted your comment to the wrong issue.

**Comment by srbala** [comment]
@AlainD- seems project is updated to newer version, please review and close

**Comment by AlainD-** [comment]
Fixed in Sigma React 3.0.0
