### ISSUE TITLE
Make this project compatible with  Yarn

### ISSUE THREAD

**Issue by usama-jamil** [primefaces/sigma#5]
when I install packages with yarn install it  conflict with the package-lock.json  with yarn.lock

**Comment by brandonkal** [comment]
@usama-jamil Of course it does. Just use [yarn import](https://yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/) and delete the package-lock.json if you'd rather use yarn to manage things. You must choose a package manager, you can't use both without issues!
